HenryBookStore/Models/AuthorFilter.cs
using HenryBookStore.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HenryBookStore.Models
{
    public class AuthorFilter


    {
        public string AuthorSelected { get; set; }

        public IEnumerable<SelectListItem> AllAuthorOptions { get; set; }
        public IEnumerable<BOOK> Books { get; set; }
    }
}

HenryBookStore/Models/LocationFilter.cs
using HenryBookStore.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HenryBookStore.Models
{
    public class LocationFilter
    {
        public string LocationSelected { get; set; }

        public IEnumerable<SelectListItem> AllLocationOptions { get; set; }
        public IEnumerable<BOOK> Books { get; set; } 
    }
}

HenryBookStore/Models/PublisherFilter.cs
using HenryBookStore.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace HenryBookStore.Models
{
    public class PublisherFilter
    {
        public string PublisherSelected { get; set; }

        public IEnumerable<SelectListItem> AllPublisherOptions { get; set; }

        public List<BOOK> Books { get; set; } 
    }
}

HenryBookStore/Controllers/AuthorFilterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HenryBookStore.Models;
using HenryBookStore.Models.EntityFramework;

namespace HenryBookStore.Controllers
{
    public class AuthorFilterController : Controller
    {
        private HENRY_ASPNETEntities db = new HENRY_ASPNETEntities();
        // GET: AuthorFilter
        public ActionResult Index()
        {
            AuthorFilter model = new AuthorFilter();
            model.AllAuthorOptions = db.AUTHORs.Select(a => new SelectListItem
            {
                Value = a.AUTHOR_NUM.ToString(),
                Text = a.AUTHOR_FIRST + ", " + a.AUTHOR_LAST
            }).ToList();

            model.Books = new List<BOOK>();
   
            return View(model);
        }





        [HttpPost]
        public ActionResult Index(AuthorFilter model)
        {
            if (string.IsNullOrEmpty(model.AuthorSelected))
            {
                // If no author is selected, reload the page with all authors
                model.AllAuthorOptions = db.AUTHORs.Select(a => new SelectListItem
                {
                    Value = a.AUTHOR_NUM.ToString(),
                    Text = a.AUTHOR_FIRST + " " + a.AUTHOR_LAST
                }).ToList();

                model.Books = new List<BOOK>(); // No books to display if no author is selected

                
                return View(model);
            }
            else
            {
                // Filter the books by the selected author
                int authorId = int.Parse(model.AuthorSelected);
                var booksByAuthor = db.WROTEs
                                      .Where(w => w.AUTHOR_NUM == authorId)
                                      .Select(w => w.BOOK)
                                      .ToList();

                model.Books = booksByAuthor; // Pass the filtered books to the view

                // Re-populate the dropdown list so it doesn't clear out 
                model.AllAuthorOptions = db.AUTHORs.Select(a => new SelectListItem
                {
                    Value = a.AUTHOR_NUM.ToString(),
                    Text = a.AUTHOR_FIRST + " " + a.AUTHOR_LAST
                }).ToList();

                return View("~/Views/Home/BrowseAuthor.cshtml",model);

            }


        }



    }
}

HenryBookStore/Controllers/LocationFilterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HenryBookStore.Models;
using HenryBookStore.Models.EntityFramework;

namespace HenryBookStore.Controllers
{
    public class LocationFilterController : Controller
    {
        private HENRY_ASPNETEntities db = new HENRY_ASPNETEntities();
        // GET: LocationFilter
        public ActionResult Index()
        {
            LocationFilter model = new LocationFilter();
            model.AllLocationOptions = db.BRANCHes.Select(b => new SelectListItem
            {
                Value = b.BRANCH_NUM.ToString(),
                Text = b.BRANCH_NAME
            }).ToList();
            return View(model); 

        }


        [HttpPost]
        public ActionResult Index(LocationFilter model)
        {
            if (string.IsNullOrEmpty(model.LocationSelected))
            {
                // If no location is selected, reload the page with all locations
                model.AllLocationOptions = db.BRANCHes.Select(b => new SelectListItem
                {
                    Value = b.BRANCH_NUM.ToString(),
                    Text = b.BRANCH_NAME
                }).ToList();

                return View(model);
            }

            // Filter the books by the selected location
            int locationId = int.Parse(model.LocationSelected);
            var booksByLocation = db.INVENTORies
                                    .Where(i => i.BRANCH_NUM == locationId)
                                    .Select(i => i.BOOK)
                                    .ToList();

            model.Books = booksByLocation;

            // Re-populate the dropdown list so it doesn't clear out 
            model.AllLocationOptions = db.BRANCHes.Select(b => new SelectListItem
            {
                Value = b.BRANCH_NUM.ToString(),
                Text = b.BRANCH_NAME
            }).ToList();

            return View(model); 
        }



    }
}

HenryBookStore/Controllers/PublisherFilterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HenryBookStore.Models;
using HenryBookStore.Models.EntityFramework;

namespace HenryBookStore.Controllers
{
    public class PublisherFilterController : Controller
    {
        private HENRY_ASPNETEntities db = new HENRY_ASPNETEntities();
        // GET: PublisherFilter
        public ActionResult Index()
        {
            PublisherFilter model = new PublisherFilter();
            model.AllPublisherOptions = db.PUBLISHERs.Select(p => new SelectListItem
            {
                Value = p.PUBLISHER_CODE.ToString(),
                Text = p.PUBLISHER_NAME
            }).ToList();
            return View(model);
        }

        // POST: PublisherFilter
        [HttpPost]
        public ActionResult Index(PublisherFilter model)
        {
            if (string.IsNullOrEmpty(model.PublisherSelected))
            {
                // If no publisher is selected, reload the page with all publishers
                model.AllPublisherOptions = db.PUBLISHERs.Select(p => new SelectListItem
                {
                    Value = p.PUBLISHER_CODE.ToString(),
                    Text = p.PUBLISHER_NAME
                }).ToList();

                return View(model);
            }

            // Filter the books by the selected publisher
            var booksByPublisher = db.BOOKs
                                     .Where(b => b.PUBLISHER_CODE == model.PublisherSelected)
                                     .ToList();

            model.Books = booksByPublisher; // Pass the filtered books to the view

            // Re-populate the dropdown list so it doesn't clear
            model.AllPublisherOptions = db.PUBLISHERs.Select(p => new SelectListItem
            {
                Value = p.PUBLISHER_CODE.ToString(),
                Text = p.PUBLISHER_NAME
            }).ToList();

            return View(model);
        }


    }
}

HenryBookStore/Views/Shared/_AuthorFilter.cshtml
@using HenryBookStore.Models;
@model HenryBookStore.Models.AuthorFilter


<h3>Search By Author</h3>


<!--Drop down list that retrieves all options-->
@using (Html.BeginForm("Index", "AuthorFilter", FormMethod.Post))
{
    <label for="author">Author</label>
    @Html.DropDownListFor(a => a.AuthorSelected, Model.AllAuthorOptions, "Please Pick an Author",
   new { onchange = "this.form.submit();" })

}

HenryBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Henry's Bookstore</title>
    <link rel="stylesheet" href="~/Content/Site.css" />
</head>
<body>


    <header>
        <img alt="BooksHeader" src="~/Content/Images/books.jpg" style="display:none;" /> 
        <h1>Henry's Bookstore</h1>
        <p class="subheader">For INTERNAL Use Only</p>
    </header>

    <!-- Main Wrapper -->
    <div class="main-wrapper">
        <!-- Sidebar Navigation -->
        <nav class="sidebar">
            <ul>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Browse Inventory", "Inventory", "Home")</li>
                <li>@Html.ActionLink("Browse by Author", "BrowseAuthor", "Home")</li>
                <li>@Html.ActionLink("Browse by Publisher", "BrowsePublisher", "Home")</li>
                <li>@Html.ActionLink("Browse by Location", "BrowseLocation", "Home")</li>
                <li>@Html.ActionLink("Contact Management", "Contact", "Home")</li>
            </ul>
        </nav>

        <!-- Main Content Area -->
        <div class="main-content">
            @RenderBody()
        </div>
    </div>

    <!-- Footer Section -->
    <footer>
        <p>This page is created for educational purposes only. No images or content will be published to the Internet for public use. Book cover images were retrieved from <a href="https://www.barnesandnoble.com">Barnes and Noble</a>.</p>
    </footer>

    <!-- Scripts -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HenryBookStore/Views/Shared/_LocationFilter.cshtml
@using HenryBookStore.Models;
@model LocationFilter


<h3>Search By Location</h3>



<!--Drop down list that retrieves all options-->
@using (Html.BeginForm("Index", "LocationFilter", FormMethod.Post))
{
    <label for="location">Location</label>
    @Html.DropDownListFor(l => l.LocationSelected, Model.AllLocationOptions, "Please Pick a Location",
    new { onchange = "this.form.submit();" })
}

HenryBookStore/Views/Shared/_PublisherFilter.cshtml
@using HenryBookStore.Models;
@model PublisherFilter


<h3>Search By Publisher</h3>


<!--Drop down list that retrieves all options-->
@using (Html.BeginForm("Index", "PublisherFilter", FormMethod.Post))
{
    <label for="publisher">Publisher</label>
    @Html.DropDownListFor(p => p.PublisherSelected, Model.AllPublisherOptions, "Please Pick a Publisher",
    new { onchange = "this.form.submit();" })
}